# Generated by Django 5.2.8 on 2026-06-20 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_asset', models.PositiveIntegerField(verbose_name='투자 가능 자산')),
                ('risk_type', models.CharField(choices=[('stable', '안정형'), ('stability_seeking', '안정추구형'), ('balanced', '균형형'), ('active', '적극투자형'), ('aggressive', '공격투자형')], max_length=32, verbose_name='투자 성향')),
                ('investment_period', models.CharField(choices=[('short', '단타'), ('swing', '스윙'), ('long', '중장기')], max_length=16, verbose_name='투자 기간')),
                ('investment_goal', models.CharField(choices=[('growth', '자산 증식'), ('stable_income', '안정적 수익'), ('dividend', '배당 수익'), ('short_profit', '단기 차익'), ('retirement', '노후 대비')], max_length=32, verbose_name='투자 목적')),
                ('investment_style', models.CharField(blank=True, choices=[('value', '가치 투자'), ('growth', '성장 투자'), ('dividend', '배당 투자'), ('momentum', '모멘텀'), ('news', '뉴스 기반')], max_length=32, verbose_name='투자 스타일')),
                ('interest_industries', models.JSONField(default=list, verbose_name='관심 산업')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
