"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env (NF103)
load_dotenv(BASE_DIR / ".env")


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 실제 키는 backend/.env 의 DJANGO_SECRET_KEY 로 관리한다(.gitignore 처리됨).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-dev-fallback-change-me"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "accounts",
    "profiles",
    "stocks",
    "recommendations",
    "news",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = ["http://localhost:5173"]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Custom user model (F100)
AUTH_USER_MODEL = "accounts.User"


# Django REST Framework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


# 토스증권 Open API (F400 시세/종목정보). 실제 키는 backend/.env 로 관리(.gitignore).
TOSS_API_BASE = os.environ.get("TOSS_API_BASE", "https://openapi.tossinvest.com")
TOSS_CLIENT_ID = os.environ.get("TOSS_CLIENT_ID", "")
TOSS_CLIENT_SECRET = os.environ.get("TOSS_CLIENT_SECRET", "")
TOSS_QUOTE_TTL_SECONDS = int(os.environ.get("TOSS_QUOTE_TTL_SECONDS", "30"))

# SSAFY GMS API (F300 추천 이유 자연어 생성). 키 미설정 시 규칙기반 템플릿으로 폴백.
GMS_API_BASE = os.environ.get("GMS_API_BASE") or "https://gms.ssafy.io/gmsapi"
GMS_API_KEY = os.environ.get("GMS_API_KEY", "")
GMS_MODEL = os.environ.get("GMS_MODEL") or "gpt-4.1"

# F300 추천 파라미터
RECOMMENDATION_TOP_N = int(os.environ.get("RECOMMENDATION_TOP_N", "5"))
METRIC_WINDOW = int(os.environ.get("METRIC_WINDOW", "60"))  # 지표 계산에 쓸 일봉 수
NEWS_SUMMARY_ENABLED = _env_bool("NEWS_SUMMARY_ENABLED", True)
NEWS_SUMMARY_TTL_HOURS = int(os.environ.get("NEWS_SUMMARY_TTL_HOURS", "6"))
NEWS_SUMMARY_LIMIT = int(os.environ.get("NEWS_SUMMARY_LIMIT", "5"))
NEWS_SUMMARY_TIMEOUT_SECONDS = int(os.environ.get("NEWS_SUMMARY_TIMEOUT_SECONDS", "5"))
NEWS_RSS_BASE = os.environ.get("NEWS_RSS_BASE") or "https://news.google.com/rss/search"

# F500 뉴스 (목록·검색·종목별·주요·스크랩). RSS(키 불필요)를 스로틀 캐시로 보호한다.
NEWS_ENABLED = _env_bool("NEWS_ENABLED", True)
NEWS_LIST_LIMIT = int(os.environ.get("NEWS_LIST_LIMIT", "20"))
NEWS_LIST_TTL_SECONDS = int(os.environ.get("NEWS_LIST_TTL_SECONDS", "600"))  # 같은 검색어 재호출 억제
NEWS_LIST_TIMEOUT_SECONDS = int(os.environ.get("NEWS_LIST_TIMEOUT_SECONDS", "5"))
NEWS_TOP_QUERY = os.environ.get("NEWS_TOP_QUERY") or "증시 OR 코스피 OR 코스닥 OR 주식시장"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
