# Generated by Django 5.2.8 on 2026-06-20 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_snapshot', models.JSONField(default=dict)),
                ('analysis_summary', models.TextField()),
                ('used_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('stock_name', models.CharField(max_length=80)),
                ('stock_code', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=40)),
                ('current_price', models.PositiveIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('reason', models.TextField()),
                ('news_title', models.CharField(blank=True, max_length=160)),
                ('news_url', models.URLField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.recommendationrun')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('run', 'rank')},
            },
        ),
    ]
