# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockNewsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_summary",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
    ]
