# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_stocknewssummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknewssummary",
            name="articles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recommendationitem",
            name="news_articles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
