# Generated by Django 6.0.6 on 2026-06-20 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="InvestmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_asset",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1천만 원 미만"),
                            (2, "1천만~5천만 원"),
                            (3, "5천만~1억 원"),
                            (4, "1억~5억 원"),
                            (5, "5억 원 이상"),
                        ]
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("STABLE", "안정형"),
                            ("STABLE_SEEKING", "안정추구형"),
                            ("BALANCED", "균형형"),
                            ("ACTIVE", "적극투자형"),
                            ("AGGRESSIVE", "공격투자형"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "investment_period",
                    models.CharField(
                        choices=[
                            ("SHORT", "단타"),
                            ("SWING", "스윙"),
                            ("LONG", "중장기"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "investment_goal",
                    models.CharField(
                        choices=[
                            ("GROWTH", "자산증식"),
                            ("STABLE_INCOME", "안정적수익"),
                            ("DIVIDEND", "배당수익"),
                            ("SHORT_TERM_GAIN", "단기차익"),
                            ("RETIREMENT", "노후대비"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        related_name="profiles", to="profiles.sector"
                    ),
                ),
            ],
        ),
    ]
