# Generated by Django 5.2.8 on 2026-06-21 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(max_length=600)),
                ('originallink', models.URLField(blank=True, max_length=600)),
                ('sector', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_scraps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'link'), name='unique_news_scrap_per_user_link')],
            },
        ),
    ]
